<?php

return [
    'roles' => [
        'super_admin' => 'Super Admin',
        'admin' => 'Admin',
        'accountant' => 'Kế toán',
        'sales' => 'Sales',
        'teacher' => 'Giáo viên',
    ],

    'groups' => [
        'overview' => [
            'label' => 'Tổng quan',
            'permissions' => [
                'dashboard.view' => 'Xem bảng điều khiển',
            ],
        ],
        'crm' => [
            'label' => 'Tuyển sinh (CRM)',
            'permissions' => [
                'crm.sales.view' => 'Dashboard Sales',
                'crm.leads.view' => 'Xem danh sách Leads',
                'crm.leads.manage' => 'Thêm / sửa / xóa Leads',
                'crm.leads.import' => 'Nhập Leads từ Excel',
                'crm.interactions.view' => 'Xem lịch hẹn / tương tác',
                'crm.interactions.manage' => 'Thêm / sửa / xóa tương tác',
            ],
        ],
        'training' => [
            'label' => 'Quản trị đào tạo',
            'permissions' => [
                'training.classes.view' => 'Xem lớp học',
                'training.classes.manage' => 'Quản lý lớp / TKB / học viên lớp',
                'training.subjects.view' => 'Xem môn học',
                'training.subjects.manage' => 'Thêm / sửa / xóa môn học',
                'training.teachers.view' => 'Xem giáo viên',
                'training.teachers.manage' => 'Thêm / sửa / xóa giáo viên',
                'training.teachers.payroll' => 'Xem / xuất bảng lương GV',
            ],
        ],
        'students' => [
            'label' => 'Quản trị học viên',
            'permissions' => [
                'students.view' => 'Xem học sinh',
                'students.manage' => 'Thêm / sửa / xóa học sinh',
                'attendances.view' => 'Xem điểm danh',
                'attendances.manage' => 'Lưu điểm danh',
            ],
        ],
        'finance' => [
            'label' => 'Quản trị tài chính',
            'permissions' => [
                'finance.dashboard.view' => 'Dashboard tài chính',
                'finance.invoices.view' => 'Xem hóa đơn học phí',
                'finance.invoices.manage' => 'Tạo / sửa / xóa hóa đơn',
                'finance.payments.manage' => 'Ghi nhận thanh toán',
                'finance.refunds.manage' => 'Hoàn tiền / duyệt hoàn',
                'finance.expenses.view' => 'Xem chi phí',
                'finance.expenses.manage' => 'Tạo / sửa chi phí',
                'finance.expenses.approve' => 'Duyệt chi phí',
                'finance.debts.view' => 'Xem công nợ',
                'finance.commissions.view' => 'Xem hoa hồng',
                'finance.commissions.manage' => 'Quản lý hoa hồng / quy tắc',
                'finance.reports.view' => 'Xem báo cáo tài chính',
                'finance.reports.export' => 'Xuất báo cáo Excel/PDF',
            ],
        ],
        'system' => [
            'label' => 'Hệ thống',
            'permissions' => [
                'system.branches.view' => 'Xem chi nhánh',
                'system.branches.manage' => 'Thêm / sửa / xóa chi nhánh',
                'system.users.view' => 'Xem người dùng',
                'system.users.manage' => 'Thêm / sửa / xóa người dùng',
                'system.permissions.manage' => 'Cấu hình phân quyền',
                'system.reports.view' => 'Xem báo cáo tổng hợp',
                'system.settings.manage' => 'Cài đặt hệ thống',
                'system.demo_data.manage' => 'Khởi tạo data demo',
            ],
        ],
    ],

    'defaults' => [
        'admin' => [
            'dashboard.view',
            'crm.sales.view',
            'crm.leads.view', 'crm.leads.manage', 'crm.leads.import',
            'crm.interactions.view', 'crm.interactions.manage',
            'training.classes.view', 'training.classes.manage',
            'training.subjects.view', 'training.subjects.manage',
            'training.teachers.view', 'training.teachers.manage', 'training.teachers.payroll',
            'students.view', 'students.manage',
            'attendances.view', 'attendances.manage',
            'finance.dashboard.view',
            'finance.invoices.view', 'finance.invoices.manage', 'finance.payments.manage',
            'finance.refunds.manage',
            'finance.expenses.view', 'finance.expenses.manage', 'finance.expenses.approve',
            'finance.debts.view',
            'finance.commissions.view', 'finance.commissions.manage',
            'finance.reports.view', 'finance.reports.export',
            'system.branches.view', 'system.branches.manage',
            'system.users.view', 'system.users.manage',
            'system.permissions.manage',
            'system.reports.view',
            'system.settings.manage',
            'system.demo_data.manage',
        ],
        'accountant' => [
            'dashboard.view',
            'students.view',
            'finance.dashboard.view',
            'finance.invoices.view', 'finance.invoices.manage', 'finance.payments.manage',
            'finance.refunds.manage',
            'finance.expenses.view', 'finance.expenses.manage',
            'finance.debts.view',
            'finance.commissions.view',
            'finance.reports.view', 'finance.reports.export',
        ],
        'sales' => [
            'dashboard.view',
            'crm.sales.view',
            'crm.leads.view', 'crm.leads.manage', 'crm.leads.import',
            'crm.interactions.view', 'crm.interactions.manage',
            'students.view',
            'finance.debts.view',
            'finance.commissions.view',
            'finance.invoices.view',
            'system.reports.view',
        ],
        'teacher' => [
            'dashboard.view',
            'training.classes.view',
            'training.teachers.view',
            'students.view',
            'attendances.view', 'attendances.manage',
        ],
    ],
];
