<?php

/**
 * Ma trận nhắc việc / tự động hóa — nguồn cho ReminderScheduler + trang admin.
 *
 * Job scheduler: key, command, interval, after, options, weekday, day (+ meta hiển thị).
 * Entry event: không có interval — kích hoạt theo thao tác nghiệp vụ.
 */
return [

    'scheduler_jobs' => [
        [
            'key' => 'tasks_create_staff_attendance',
            'command' => 'tasks:create-staff-attendance',
            'after' => '05:30',
            'interval' => 'daily',
            'group' => 'Nhân sự',
            'label' => 'Chấm công nhân viên',
            'schedule_label' => 'Mỗi ngày làm việc, sau 05:30 (tick đầu tiên trong ngày)',
            'output' => 'task',
            'source_type' => 'staff_attendance',
            'assignee' => 'system.staff_attendances.manage (theo CN)',
            'notifications' => '—',
            'close_when' => 'Đã chấm công đủ / xong ngày',
            'notes' => 'Theo Cài đặt → Ngày làm việc',
        ],
        [
            'key' => 'tasks_create_today_sessions',
            'command' => 'tasks:create-today-sessions',
            'after' => '05:45',
            'interval' => 'daily',
            'group' => 'Đào tạo',
            'label' => 'Buổi học hôm nay',
            'schedule_label' => 'Mỗi ngày, sau 05:45',
            'output' => 'task',
            'source_type' => 'session_today',
            'assignee' => 'GV (email) hoặc training.classes.manage',
            'notifications' => '—',
            'close_when' => 'Hoàn thành / hủy buổi',
            'notes' => 'Chỉ buổi scheduled trong ngày',
        ],
        [
            'key' => 'system_remind_backup',
            'command' => 'system:remind-backup',
            'after' => '06:00',
            'interval' => 'weekly',
            'weekday' => 1,
            'group' => 'Hệ thống',
            'label' => 'Nhắc backup CSDL',
            'schedule_label' => 'Thứ 2, sau 06:00',
            'output' => 'task',
            'source_type' => 'backup',
            'assignee' => 'system.backups.manage',
            'notifications' => '—',
            'close_when' => 'Tạo backup',
            'notes' => '',
        ],
        [
            'key' => 'finance_remind_debts',
            'command' => 'finance:remind-debts',
            'options' => ['--days' => 3],
            'after' => '08:00',
            'interval' => 'daily',
            'group' => 'Tài chính',
            'label' => 'Nhắc nợ học phí',
            'schedule_label' => 'Mỗi ngày, sau 08:00',
            'output' => 'both',
            'source_type' => 'invoice_debt',
            'assignee' => 'Kế toán / quyền thu nợ',
            'notifications' => 'In-app, Email, Zalo PH',
            'close_when' => 'Thu đủ / ghi nhận TT',
            'notes' => 'Zalo: zalo_notify_debt',
        ],
        [
            'key' => 'crm_remind_lead_followups',
            'command' => 'crm:remind-lead-followups',
            'options' => ['--days' => 1],
            'after' => '08:15',
            'interval' => 'daily',
            'group' => 'CRM',
            'label' => 'Follow-up lead',
            'schedule_label' => 'Mỗi ngày, sau 08:15',
            'output' => 'task',
            'source_type' => 'lead_followup',
            'assignee' => 'Sales được gán lead',
            'notifications' => 'In-app (lead)',
            'close_when' => 'Lead won/lost / xử lý',
            'notes' => 'Cả khi gán lead (event)',
        ],
        [
            'key' => 'crm_remind_interactions',
            'command' => 'crm:remind-interactions',
            'options' => ['--hours' => 48, '--overdue-days' => 3],
            'interval' => 'hourly',
            'group' => 'CRM',
            'label' => 'Đồng bộ lịch hẹn CRM',
            'schedule_label' => 'Mỗi giờ (tick trong giờ)',
            'output' => 'task',
            'source_type' => 'interaction',
            'assignee' => 'Sales trên tương tác',
            'notifications' => '—',
            'close_when' => 'Hoàn thành / hủy lịch',
            'notes' => 'Cả khi tạo/sửa tương tác',
        ],
        [
            'key' => 'crm_remind_stale_sessions',
            'command' => 'crm:remind-stale-sessions',
            'options' => ['--days' => 7],
            'interval' => 'hourly',
            'group' => 'Đào tạo',
            'label' => 'Buổi quá hạn chưa cập nhật',
            'schedule_label' => 'Mỗi giờ',
            'output' => 'task',
            'source_type' => 'session_status',
            'assignee' => 'training.classes.manage',
            'notifications' => 'In-app',
            'close_when' => 'Đổi trạng thái buổi',
            'notes' => '',
        ],
        [
            'key' => 'crm_remind_empty_journals',
            'command' => 'crm:remind-empty-journals',
            'options' => ['--days' => 14],
            'interval' => 'hourly',
            'group' => 'Đào tạo',
            'label' => 'Nhật ký buổi trống',
            'schedule_label' => 'Mỗi giờ',
            'output' => 'task',
            'source_type' => 'session_journal',
            'assignee' => 'GV / training.journals.manage',
            'notifications' => 'In-app',
            'close_when' => 'Ghi nhật ký',
            'notes' => 'Cả sau khi hoàn thành buổi',
        ],
        [
            'key' => 'crm_remind_upcoming_sessions',
            'command' => 'crm:remind-upcoming-sessions',
            'options' => ['--minutes' => 120, '--window' => 12],
            'interval' => 'every_15m',
            'group' => 'Đào tạo',
            'label' => 'Nhắc trước buổi học',
            'schedule_label' => 'Mỗi ~15 phút (cửa sổ ±12 phút quanh mốc −2h)',
            'output' => 'notify',
            'source_type' => '—',
            'assignee' => 'HV / PH (Email, Zalo)',
            'notifications' => 'Mẫu session_reminder',
            'close_when' => '—',
            'notes' => 'Không tạo task board',
        ],
        [
            'key' => 'tasks_remind_deadlines',
            'command' => 'tasks:remind-deadlines',
            'interval' => 'hourly',
            'group' => 'Công việc',
            'label' => 'Nhắc hạn task',
            'schedule_label' => 'Mỗi giờ',
            'output' => 'notify',
            'source_type' => '—',
            'assignee' => 'Người được giao task',
            'notifications' => 'In-app (TaskEvent)',
            'close_when' => '—',
            'notes' => '1d / 3h / trong ngày / quá hạn',
        ],
        [
            'key' => 'finance_remind_monthly_invoices',
            'command' => 'finance:remind-monthly-invoices',
            'after' => '07:00',
            'interval' => 'monthly',
            'day' => 1,
            'group' => 'Tài chính',
            'label' => 'Thu học phí tháng',
            'schedule_label' => 'Ngày 1 hàng tháng, sau 07:00',
            'output' => 'task',
            'source_type' => 'monthly_invoice',
            'assignee' => 'finance.invoices.manage',
            'notifications' => '—',
            'close_when' => 'Xử lý thu tháng',
            'notes' => '',
        ],
        [
            'key' => 'finance_remind_payroll',
            'command' => 'finance:remind-payroll',
            'after' => '07:00',
            'interval' => 'monthly',
            'day' => 31,
            'group' => 'Tài chính',
            'label' => 'Chốt lương GV & NV',
            'schedule_label' => 'Cuối tháng, sau 07:00 (tháng lương = tháng trước)',
            'output' => 'task',
            'source_type' => 'teacher_payroll, staff_payroll',
            'assignee' => 'training.teachers.payroll, finance.staff_payroll.view',
            'notifications' => '—',
            'close_when' => 'Chốt / chi lương',
            'notes' => '',
        ],
        [
            'key' => 'finance_remind_commissions',
            'command' => 'finance:remind-commissions',
            'after' => '07:00',
            'interval' => 'monthly',
            'day' => 28,
            'group' => 'Tài chính',
            'label' => 'Chốt hoa hồng Sales',
            'schedule_label' => 'Ngày 28, sau 07:00',
            'output' => 'task',
            'source_type' => 'commission_month',
            'assignee' => 'finance.commissions.manage/view',
            'notifications' => '—',
            'close_when' => 'Đánh dấu đã trả HH',
            'notes' => '',
        ],
    ],

    'event_entries' => [
        [
            'group' => 'CRM',
            'label' => 'Tạo / sửa lịch hẹn',
            'trigger' => 'Lưu Interaction',
            'output' => 'task',
            'source_type' => 'interaction',
            'assignee' => 'Sales trên tương tác',
            'notifications' => '—',
            'close_when' => 'Xong lịch hẹn',
            'notes' => 'InteractionTaskService',
        ],
        [
            'group' => 'CRM',
            'label' => 'Phân bổ lead cho Sales',
            'trigger' => 'Gán assigned_sales',
            'output' => 'task',
            'source_type' => 'lead_followup',
            'assignee' => 'Sales được gán',
            'notifications' => 'In-app phân lead',
            'close_when' => 'Pipeline lead',
            'notes' => 'LeadAssignmentNotifier',
        ],
        [
            'group' => 'Đào tạo',
            'label' => 'Hoàn thành buổi học',
            'trigger' => 'Đổi status buổi → completed',
            'output' => 'both',
            'source_type' => 'session_journal, session_today, session_status',
            'assignee' => 'GV / Đào tạo',
            'notifications' => 'Nhắc ghi nhật ký',
            'close_when' => 'Nhật ký + trạng thái',
            'notes' => 'ClassController, Notifier',
        ],
        [
            'group' => 'Tài chính',
            'label' => 'Tạo đề nghị chi',
            'trigger' => 'Tạo expense',
            'output' => 'task',
            'source_type' => 'expense_approve',
            'assignee' => 'finance.expenses.approve',
            'notifications' => 'In-app',
            'close_when' => 'Duyệt / từ chối',
            'notes' => '',
        ],
        [
            'group' => 'Tài chính',
            'label' => 'Chi phí chờ chi',
            'trigger' => 'Duyệt expense',
            'output' => 'task',
            'source_type' => 'expense_pay',
            'assignee' => 'finance.expenses.pay',
            'notifications' => '—',
            'close_when' => 'Đã chi',
            'notes' => '',
        ],
        [
            'group' => 'Tài chính',
            'label' => 'Yêu cầu hoàn tiền',
            'trigger' => 'Tạo refund',
            'output' => 'task',
            'source_type' => 'refund_approve',
            'assignee' => 'Người duyệt hoàn',
            'notifications' => 'In-app',
            'close_when' => 'Duyệt / từ chối',
            'notes' => '',
        ],
        [
            'group' => 'Tài chính',
            'label' => 'Ghi nhận thanh toán HĐ',
            'trigger' => 'PaymentService',
            'output' => 'notify',
            'source_type' => 'invoice_debt (đóng)',
            'assignee' => 'HV / PH',
            'notifications' => 'Email + ZNS thanh toán',
            'close_when' => '—',
            'notes' => 'zalo_notify_payment',
        ],
        [
            'group' => 'Công việc',
            'label' => 'Công bố task thủ công',
            'trigger' => 'Publish task',
            'output' => 'notify',
            'source_type' => '—',
            'assignee' => 'Assignee + watchers',
            'notifications' => 'TaskEventNotification',
            'close_when' => '—',
            'notes' => 'Không áp dụng auto task',
        ],
    ],

];
