<?php

/**
 * Ma trận nhắc việc — nguồn cho ReminderScheduler + trang /admin/reminder-matrix.
 * Field kỹ thuật: key, command, interval, after, options, weekday, day.
 */
return [

    'scheduler_jobs' => [
        [
            'key' => 'tasks_create_staff_attendance',
            'command' => 'tasks:create-staff-attendance',
            'after' => '05:30',
            'interval' => 'daily',
            'group' => 'Nhân sự',
            'label' => 'Chấm công nhân viên',
            'schedule_label' => 'Mỗi ngày làm việc, sáng (sau 5h30)',
            'output' => 'task',
            'source_type' => 'staff_attendance',
            'assignee' => 'Người được phép chấm công NV',
            'notifications' => '—',
            'close_when' => 'Đã chấm công xong',
            'notes' => 'Theo mục Ngày làm việc trong Cài đặt',
        ],
        [
            'key' => 'tasks_create_today_sessions',
            'command' => 'tasks:create-today-sessions',
            'after' => '05:45',
            'interval' => 'daily',
            'group' => 'Đào tạo',
            'label' => 'Buổi học hôm nay',
            'schedule_label' => 'Mỗi ngày, sáng (sau 5h45)',
            'output' => 'task',
            'source_type' => 'session_today',
            'assignee' => 'Giáo viên lớp hoặc bộ phận Đào tạo',
            'notifications' => '—',
            'close_when' => 'Buổi học hoàn thành hoặc hủy',
            'notes' => 'Chỉ lớp có buổi học trong ngày',
        ],
        [
            'key' => 'system_remind_backup',
            'command' => 'system:remind-backup',
            'after' => '06:00',
            'interval' => 'weekly',
            'weekday' => 1,
            'group' => 'Hệ thống',
            'label' => 'Sao lưu dữ liệu',
            'schedule_label' => 'Thứ Hai hàng tuần, sáng (sau 6h)',
            'output' => 'task',
            'source_type' => 'backup',
            'assignee' => 'Người quản trị backup',
            'notifications' => '—',
            'close_when' => 'Đã tạo bản sao lưu',
            'notes' => '',
        ],
        [
            'key' => 'finance_remind_debts',
            'command' => 'finance:remind-debts',
            'options' => ['--days' => 3],
            'after' => '08:00',
            'interval' => 'daily',
            'group' => 'Tài chính',
            'label' => 'Nhắc nợ học phí',
            'schedule_label' => 'Mỗi ngày, sau 8h sáng',
            'output' => 'both',
            'source_type' => 'invoice_debt',
            'assignee' => 'Kế toán / thu học phí',
            'notifications' => 'Chuông app, Email, Zalo phụ huynh',
            'close_when' => 'Đã thu đủ hoặc ghi nhận thanh toán',
            'notes' => 'Cần bật Zalo nhắc nợ trong Cài đặt',
        ],
        [
            'key' => 'crm_remind_lead_followups',
            'command' => 'crm:remind-lead-followups',
            'options' => ['--days' => 1],
            'after' => '08:15',
            'interval' => 'daily',
            'group' => 'CRM',
            'label' => 'Follow-up khách lead',
            'schedule_label' => 'Mỗi ngày, sau 8h15',
            'output' => 'task',
            'source_type' => 'lead_followup',
            'assignee' => 'Sales phụ trách lead',
            'notifications' => 'Chuông app',
            'close_when' => 'Lead chốt, thất bại hoặc đã xử lý',
            'notes' => 'Cũng tạo khi gán lead cho Sales',
        ],
        [
            'key' => 'crm_remind_interactions',
            'command' => 'crm:remind-interactions',
            'options' => ['--hours' => 48, '--overdue-days' => 3],
            'interval' => 'hourly',
            'group' => 'CRM',
            'label' => 'Lịch hẹn / tương tác CRM',
            'schedule_label' => 'Kiểm tra mỗi giờ',
            'output' => 'task',
            'source_type' => 'interaction',
            'assignee' => 'Sales trên lịch hẹn',
            'notifications' => '—',
            'close_when' => 'Hoàn thành hoặc hủy lịch',
            'notes' => 'Cũng cập nhật khi thêm/sửa lịch hẹn',
        ],
        [
            'key' => 'crm_remind_stale_sessions',
            'command' => 'crm:remind-stale-sessions',
            'options' => ['--days' => 7],
            'interval' => 'hourly',
            'group' => 'Đào tạo',
            'label' => 'Buổi học quá hạn chưa cập nhật',
            'schedule_label' => 'Kiểm tra mỗi giờ',
            'output' => 'task',
            'source_type' => 'session_status',
            'assignee' => 'Bộ phận Đào tạo',
            'notifications' => 'Chuông app',
            'close_when' => 'Đã cập nhật trạng thái buổi',
            'notes' => '',
        ],
        [
            'key' => 'crm_remind_empty_journals',
            'command' => 'crm:remind-empty-journals',
            'options' => ['--days' => 14],
            'interval' => 'hourly',
            'group' => 'Đào tạo',
            'label' => 'Nhật ký buổi học còn trống',
            'schedule_label' => 'Kiểm tra mỗi giờ',
            'output' => 'task',
            'source_type' => 'session_journal',
            'assignee' => 'Giáo viên hoặc Đào tạo',
            'notifications' => 'Chuông app',
            'close_when' => 'Đã ghi nhật ký',
            'notes' => 'Thường sau khi đánh dấu buổi hoàn thành',
        ],
        [
            'key' => 'crm_remind_upcoming_sessions',
            'command' => 'crm:remind-upcoming-sessions',
            'options' => ['--minutes' => 120, '--window' => 12],
            'interval' => 'every_15m',
            'group' => 'Đào tạo',
            'label' => 'Nhắc trước giờ học',
            'schedule_label' => 'Liên tục trong ngày (khoảng 2 giờ trước buổi)',
            'output' => 'notify',
            'source_type' => '—',
            'assignee' => 'Học viên và phụ huynh',
            'notifications' => 'Email và Zalo (mẫu tin trước buổi học)',
            'close_when' => '—',
            'notes' => 'Không tạo việc trên board Công việc',
        ],
        [
            'key' => 'tasks_remind_deadlines',
            'command' => 'tasks:remind-deadlines',
            'interval' => 'hourly',
            'group' => 'Công việc',
            'label' => 'Nhắc hạn công việc',
            'schedule_label' => 'Kiểm tra mỗi giờ',
            'output' => 'notify',
            'source_type' => '—',
            'assignee' => 'Người được giao việc',
            'notifications' => 'Chuông app',
            'close_when' => '—',
            'notes' => 'Nhắc trước 1 ngày, 3 giờ, trong ngày và quá hạn',
        ],
        [
            'key' => 'finance_remind_monthly_invoices',
            'command' => 'finance:remind-monthly-invoices',
            'after' => '07:00',
            'interval' => 'monthly',
            'day' => 1,
            'group' => 'Tài chính',
            'label' => 'Thu học phí đầu tháng',
            'schedule_label' => 'Ngày 1 hàng tháng, sáng (sau 7h)',
            'output' => 'task',
            'source_type' => 'monthly_invoice',
            'assignee' => 'Kế toán / thu học phí',
            'notifications' => '—',
            'close_when' => 'Đã xử lý thu tháng',
            'notes' => '',
        ],
        [
            'key' => 'finance_remind_payroll',
            'command' => 'finance:remind-payroll',
            'after' => '07:00',
            'interval' => 'monthly',
            'day' => 31,
            'group' => 'Tài chính',
            'label' => 'Chốt lương giáo viên & nhân viên',
            'schedule_label' => 'Cuối tháng, sáng (sau 7h) — lương tháng trước',
            'output' => 'task',
            'source_type' => 'teacher_payroll, staff_payroll',
            'assignee' => 'Người phụ trách lương GV và lương NV',
            'notifications' => '—',
            'close_when' => 'Đã chốt / chi lương',
            'notes' => '',
        ],
        [
            'key' => 'finance_remind_commissions',
            'command' => 'finance:remind-commissions',
            'after' => '07:00',
            'interval' => 'monthly',
            'day' => 28,
            'group' => 'Tài chính',
            'label' => 'Chốt hoa hồng Sales',
            'schedule_label' => 'Ngày 28 hàng tháng, sáng (sau 7h)',
            'output' => 'task',
            'source_type' => 'commission_month',
            'assignee' => 'Kế toán / quản lý hoa hồng',
            'notifications' => '—',
            'close_when' => 'Đã trả hoa hồng',
            'notes' => '',
        ],
    ],

    'event_entries' => [
        [
            'group' => 'CRM',
            'label' => 'Lịch hẹn / tương tác mới',
            'trigger' => 'Khi lưu lịch hẹn CRM',
            'output' => 'task',
            'source_type' => 'interaction',
            'assignee' => 'Sales trên lịch hẹn',
            'notifications' => '—',
            'close_when' => 'Lịch hẹn hoàn thành hoặc hủy',
            'notes' => '',
        ],
        [
            'group' => 'CRM',
            'label' => 'Lead gán cho Sales',
            'trigger' => 'Khi phân bổ lead',
            'output' => 'task',
            'source_type' => 'lead_followup',
            'assignee' => 'Sales được gán',
            'notifications' => 'Chuông app (phân lead)',
            'close_when' => 'Lead được xử lý xong',
            'notes' => '',
        ],
        [
            'group' => 'Đào tạo',
            'label' => 'Sau khi hoàn thành buổi học',
            'trigger' => 'Khi đánh dấu buổi học hoàn thành',
            'output' => 'both',
            'source_type' => 'session_journal, session_today, session_status',
            'assignee' => 'Giáo viên và Đào tạo',
            'notifications' => 'Nhắc ghi nhật ký',
            'close_when' => 'Nhật ký và trạng thái buổi đủ',
            'notes' => '',
        ],
        [
            'group' => 'Tài chính',
            'label' => 'Đề nghị chi mới',
            'trigger' => 'Khi tạo phiếu chi',
            'output' => 'task',
            'source_type' => 'expense_approve',
            'assignee' => 'Người duyệt chi',
            'notifications' => 'Chuông app',
            'close_when' => 'Duyệt hoặc từ chối',
            'notes' => '',
        ],
        [
            'group' => 'Tài chính',
            'label' => 'Chi phí đã duyệt, chờ chi tiền',
            'trigger' => 'Sau khi duyệt chi',
            'output' => 'task',
            'source_type' => 'expense_pay',
            'assignee' => 'Kế toán chi tiền',
            'notifications' => '—',
            'close_when' => 'Đã chi',
            'notes' => '',
        ],
        [
            'group' => 'Tài chính',
            'label' => 'Yêu cầu hoàn tiền',
            'trigger' => 'Khi tạo yêu cầu hoàn',
            'output' => 'task',
            'source_type' => 'refund_approve',
            'assignee' => 'Người duyệt hoàn tiền',
            'notifications' => 'Chuông app',
            'close_when' => 'Duyệt hoặc từ chối',
            'notes' => '',
        ],
        [
            'group' => 'Tài chính',
            'label' => 'Xác nhận thu học phí',
            'trigger' => 'Khi ghi nhận thanh toán hóa đơn',
            'output' => 'notify',
            'source_type' => 'invoice_debt (đóng)',
            'assignee' => 'Học viên / phụ huynh',
            'notifications' => 'Email và Zalo xác nhận thanh toán',
            'close_when' => '—',
            'notes' => 'Đồng thời đóng việc nhắc nợ nếu có',
        ],
        [
            'group' => 'Công việc',
            'label' => 'Công bố công việc mới',
            'trigger' => 'Khi bấm Công bố trên board Công việc',
            'output' => 'notify',
            'source_type' => '—',
            'assignee' => 'Người thực hiện và người liên quan',
            'notifications' => 'Chuông app',
            'close_when' => '—',
            'notes' => 'Việc tạo tay, không phải auto',
        ],
    ],

];
